# https://grafana.com/docs/loki/latest/configuration/examples/
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 15m

schema_config:
  configs:
  - from: 2019-06-01
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h
  - from: 2021-09-21
    store: aws
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h
      # tags:
      #   app: loki
      #   env: development

storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
  aws:
    s3: s3://user:password@minio:9090/chunks
    s3forcepathstyle: true
    dynamodb:
#      dynamodb_url: dynamodb://access_key:secret_access_key@region
      dynamodb_url: dynamodb://dynamodb.local:8000

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

table_manager:
  retention_period: 168h
